from app.schemas.admin import *
from app.schemas.classroom import *
from app.schemas.danceStyle import *
from app.schemas.event import *
from app.schemas.eventType import *
from app.schemas.group import *
from app.schemas.lesson import *
from app.schemas.lessonType import *
from app.schemas.level import *
from app.schemas.payment import *
from app.schemas.paymentType import *
from app.schemas.slot import *
from app.schemas.statistics import *
from app.schemas.student import *
from app.schemas.subscription import *
from app.schemas.subscriptionTemplate import *
from app.schemas.teacher import *
from app.schemas.token import *
from app.schemas.user import *
